# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/aymerick/raymond"

[[constraint]]
  branch = "master"
  name = "github.com/commondream/egon"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/htmlmin"

[[constraint]]
  branch = "master"
  name = "github.com/hoisie/mustache"

[[constraint]]
  branch = "master"
  name = "github.com/sipin/gorazor"

[[constraint]]
  branch = "master"
  name = "github.com/valyala/bytebufferpool"

[[constraint]]
  branch = "master"
  name = "github.com/valyala/quicktemplate"

[[constraint]]
  name = "github.com/yosssi/ace"
  version = "0.0.5"

[[constraint]]
  branch = "master"
  name = "github.com/ziutek/kasia.go"

[[constraint]]
  branch = "master"
  name = "github.com/eknkc/amber"

[[constraint]]
  branch = "master"
  name = "github.com/CloudyKit/jet"

[[constraint]]
  branch = "master"
  name = "github.com/flosch/pongo2"

[[constraint]]
  branch = "master"
  name = "github.com/robfig/soy"

[prune]
  go-tests = true
  unused-packages = true
